### PR TITLE
Terms and label missing fixed

### LINKED ISSUE #267: Terms and Labels missing at some instances.
Terms and Labels as set in web are not being displayed at some points in the mobile app.

Highlighted in screenshots below:
Screenshot_20190709-150155_Fieldsight
Screenshot_20190709-150211_Fieldsight
Screenshot_20190709-150241_Fieldsight

### PR DESCRIPTION
**Pull request by yubarajpoudel**
Closes #267 

To test this,

Login with santosh user and test in Kathmandu project in live.

### CODE REVIEW

**Comment by yubarajpoudel** [comment]
[[Mobile] Terms and Labels missing at some instances.](https://trello.com/c/gu9Kbgu9/695-mobile-terms-and-labels-missing-at-some-instances)

File: collect_app/src/main/java/org/fieldsight/naxa/site/SiteListFragment.java [hunk 1]
```diff
@@ -130,6 +148,24 @@ private void changeActionVisibility(boolean visible) {
...
+        if(loadedProject == null) {
+            return null;
+        }
+        if(!TextUtils.isEmpty(loadedProject.getTerms_and_labels())) {
+            try{
+                Timber.i("ProjectDashBoardActivity:: terms and labels = %s", loadedProject.getTerms_and_labels());
+                JSONObject tlJson = new JSONObject(loadedProject.getTerms_and_labels());
+                return TermsLabels.fromJSON(tlJson);
+            }catch (Exception e){
+                e.printStackTrace();
```
Comment (konishon) [inline collect_app/src/main/java/org/fieldsight/naxa/site/SiteListFragment.java:163]: Could there be any case where `getTerms_and_labels()` could return null or a improper json ?

**Review by konishon — APPROVED** [review]
