### PR TITLE
Fcm issues fixed

### LINKED ISSUE #155: FCM facing issues

### PR DESCRIPTION
**Pull request by hereyubaraj**
Closes #155

### CODE REVIEW

File: collect_app/src/main/java/org/bcss/collect/android/application/Collect.java [hunk 1]
```diff
@@ -329,14 +330,15 @@ public void onCreate() {
...
-    void createNewFcmTokenIfNotExists() {
+    public void createNewFcmTokenIfNotExists() {
         String savedFcm = SharedPreferenceUtils.getFromPrefs(this, SharedPreferenceUtils.PREF_VALUE_KEY.KEY_FCM, "");
         if(TextUtils.isEmpty(savedFcm)) {
             FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener(instanceIdResult -> {
                 String fcm_token = instanceIdResult.getToken();
                 Timber.i("Regenerated Fcm token :: %s ", fcm_token);
                 SharedPreferenceUtils.saveToPrefs(this, SharedPreferenceUtils.PREF_VALUE_KEY.KEY_FCM, savedFcm);
                 Timber.i("token saved to pref");
+                ToastUtils.showShortToast("Token generated successfully");
```
Comment (konishon) [inline collect_app/src/main/java/org/bcss/collect/android/application/Collect.java]: Please remove this toast

**Review by konishon — CHANGES_REQUESTED** [review]

**Review by konishon — APPROVED** [review]
