### PR TITLE
Previous submission view crash fixed

### LINKED ISSUE #264: App crashes when tapping 'View Submission'
Steps explained in video linked below.

https://photos.app.goo.gl/S39hsmVri6JyNDvf9

### PR DESCRIPTION
**Pull request by yubarajpoudel**
Closes #264

### CODE REVIEW

**Review by santoshkhatrii — COMMENTED** [review]
The data are seen while inspecting but not shown in the mobile app.

File: collect_app/src/main/java/org/bcss/collect/naxa/submissions/PreviousSubmissionListActivity.java [hunk 1]
```diff
@@ -298,34 +301,40 @@ public boolean isLoading() {
     }
 
     private void loadNextPage() {
-        ServiceGenerator.createCacheService(ApiInterface.class)
+        ServiceGenerator.createService(ApiInterface.class)
```
Comment (konishon) [inline collect_app/src/main/java/org/bcss/collect/naxa/submissions/PreviousSubmissionListActivity.java:304]: we used to use http cache to store ! submission that were already downloaded
Are we removing that feature altogehter with this commit?

Comment (konishon) [reply collect_app/src/main/java/org/bcss/collect/naxa/submissions/PreviousSubmissionListActivity.java:304]: @hereyubaraj like we discussed, I have made the changes
